spring:
  datasource:
    url: jdbc:mysql://localhost:3306/code_doc_system?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8080
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true